---
title: "bdlim {[regimes](http://anderwilson.github.io/regimes/)}"
output:
  html_document:
    css: style.css
    theme: cerulean
    highlight: tango
    includes:
      before_body: doc_suffix.html
---



## Bayesian Distributed Lag Interaction Models
[Ander Wilson](http://anderwilson.github.io/)

### An Example
Load the **regimes** package, simulate data, and fit BDLIM with all four options (BDLIM-n, BDLIM-b, BSLIM-w, BDLIM-bw).
```{r, message=FALSE, results='hide'}
#load package
library(regimes)
#simulate data from scenario 3
dat <- simregimes(scenario="bdlim2", seed=1234, n=1000)

#estimate model
fit <- bdlim(dat$Y,dat$X,dat$Z,dat$G,"all",niter=1000,nburn=500,nthin=1,
             prior = list(sigma=c(0.01,0.01), beta=10,gamma=10),
             basis.opts = list(knots=15, type="face", pve=.99),
             seed=1234)
```

Now display some results using the summary method.
```{r}
#summary
sfit <- summary(fit)
names(sfit)
sfit

```

Now display some results via plots.
```{r}
plot(sfit, print=TRUE)
```


