---
title: "[regimes](http://anderwilson.github.io/regimes/)"
output:
  html_document:
    css: style.css
    theme: cerulean
    highlight: tango
    includes:
      after_body: doc_suffix.html
---


## REGression In Multivariate Exposure Settings
[Ander Wilson](http://anderwilson.github.io/)

### Overview

The **regimes** R packages contains regression methods for estimating the relationship between a multivariate exposure and an outcome. The package is oriented toward environmental health and environmental epidemiology research but is applicable in a variety of settings. 


### Installation

The **regimes** package can be installed using **devtools**.
```{r, message=FALSE, warning=FALSE, eval=FALSE}
library(devtools)
devtools::install_github(repo="AnderWilson/regimes")
library(regimes)
```



### Methods

[acpme](http://anderwilson.github.io/regimes/acpme.html): adjustment for confounding in the presence of multivariate exposures

[new implementation of bdlim](http://anderwilson.github.io/bdlim/): Bayesian distributed lag interaction models implemented in new package bdlim. This is the recommended package to use for BDLIM.

[older implementation of bdlim](http://anderwilson.github.io/regimes/bdlim.html): Bayesian distributed lag interaction models. This will be removed from the package in the future.

[bkmrdlm](http://anderwilson.github.io/regimes/bkmrdlm.html): Bayesian kernel machine regression distributed lag models
