# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Estimates the BKMR-DLM for a multiple time-varying predictor.
#'
#' @param yz a matrix that is cbind(y,Z) where Z is a matrix of covariates that does not include an intercept and y is the vector of outcomes.
#' @param Xlist a list of matrices each for a single exposure in time order.
#' @param b1 first parameter for prior on tau^{-2} in the text.
#' @param a1 first parameter for prior on sigma^{-2}.
#' @param a2 second parameter for prior on sigma^{-2}.
#' @param kappa scale parameter, rho/kappa~chisq(1).
#' @param n_inner number of MCMC iterations to run in the inner loop.  This is equivelent the the thinning number.  n_outer*n_inner iteraction will be run and n_outer iterations will be saved.
#' @param n_outer number of MCMC iteration in the outer loop.   The output for each is saved.
#' @param n_burn number of MCMC iteration to be discarded as burn-in.
#' @param d the degree of polynomial for a polynomial kernel.
#' @export
bkmrdlm_multi_polynomial <- function(yz, Xlist, b1, a1, a2, kappa, n_inner, n_outer, n_burn, d) {
    .Call('_regimes_bkmrdlm_multi_polynomial', PACKAGE = 'regimes', yz, Xlist, b1, a1, a2, kappa, n_inner, n_outer, n_burn, d)
}

#' Estimates the BKMR-DLM for a multiple time-varying predictor.
#'
#' @param yz a matrix that is cbind(y,Z) where Z is a matrix of covariates that does not include an intercept and y is the vector of outcomes.
#' @param Xlist a list of matrices each for a single exposure in time order.
#' @param b1 first parameter for prior on tau^{-2} in the text.
#' @param a1 first parameter for prior on sigma^{-2}.
#' @param a2 second parameter for prior on sigma^{-2}.
#' @param kappa scale parameter, rho/kappa~chisq(1).
#' @param n_inner number of MCMC iterations to run in the inner loop.  This is equivelent the the thinning number.  n_outer*n_inner iteraction will be run and n_outer iterations will be saved.
#' @param n_outer number of MCMC iteration in the outer loop.   The output for each is saved.
#' @param n_burn number of MCMC iteration to be discarded as burn-in.
#' @param d the degree of polynomial for a polynomial kernel.
#' @export
bkmrdlm_multi_shrink_polynomial <- function(yz, Xlist, b1, a1, a2, kappa, n_inner, n_outer, n_burn, d) {
    .Call('_regimes_bkmrdlm_multi_shrink_polynomial', PACKAGE = 'regimes', yz, Xlist, b1, a1, a2, kappa, n_inner, n_outer, n_burn, d)
}

#' Estimates the BKMR-DLM for a multiple time-varying predictor.
#'
#' @param yz a matrix that is cbind(y,Z) where Z is a matrix of covariates that does not include an intercept and y is the vector of outcomes.
#' @param Xlist a list of matrices each for a single exposure in time order.
#' @param b1 first parameter for prior on tau^{-2} in the text.
#' @param a1 first parameter for prior on sigma^{-2}.
#' @param a2 second parameter for prior on sigma^{-2}.
#' @param kappa scale parameter, rho/kappa~chisq(1).
#' @param n_inner number of MCMC iterations to run in the inner loop.  This is equivelent the the thinning number.  n_outer*n_inner iteraction will be run and n_outer iterations will be saved.
#' @param n_outer number of MCMC iteration in the outer loop.   The output for each is saved.
#' @param n_burn number of MCMC iteration to be discarded as burn-in.
#' @export
bkmrdlm_multi_shrink <- function(yz, Xlist, b1, a1, a2, kappa, n_inner, n_outer, n_burn) {
    .Call('_regimes_bkmrdlm_multi_shrink', PACKAGE = 'regimes', yz, Xlist, b1, a1, a2, kappa, n_inner, n_outer, n_burn)
}

#' Estimates the BKMR-DLM for a multiple time-varying predictor.
#'
#' @param yz a matrix that is cbind(y,Z) where Z is a matrix of covariates that does not include an intercept and y is the vector of outcomes.
#' @param Xlist a list of matrices each for a single exposure in time order.
#' @param b1 first parameter for prior on tau^{-2} in the text.
#' @param a1 first parameter for prior on sigma^{-2}.
#' @param a2 second parameter for prior on sigma^{-2}.
#' @param kappa scale parameter, rho/kappa~chisq(1).
#' @param n_inner number of MCMC iterations to run in the inner loop.  This is equivelent the the thinning number.  n_outer*n_inner iteraction will be run and n_outer iterations will be saved.
#' @param n_outer number of MCMC iteration in the outer loop.   The output for each is saved.
#' @param n_burn number of MCMC iteration to be discarded as burn-in.
#' @export
bkmrdlm_multi <- function(yz, Xlist, b1, a1, a2, kappa, n_inner, n_outer, n_burn) {
    .Call('_regimes_bkmrdlm_multi', PACKAGE = 'regimes', yz, Xlist, b1, a1, a2, kappa, n_inner, n_outer, n_burn)
}

